import os

files_to_translate = {
    'products.html': [
        ('<h3>Bộ lọc sản phẩm</h3>', '<h3>Product Filters</h3>'),
        ('Xóa bộ lọc', 'Clear filters'),
        ('<h4 class="filter-title">Mùa vụ</h4>', '<h4 class="filter-title">Seasonality</h4>'),
        ('<span>Tất cả các mùa</span>', '<span>All Seasons</span>'),
        ('<span>Đặc sản theo mùa</span>', '<span>Seasonal Specialties</span>'),
        ('<span>Mùa hè</span>', '<span>Summer</span>'),
        ('<span>Mùa đông</span>', '<span>Winter</span>'),
        ('<span>Có quanh năm</span>', '<span>Year-round</span>'),
        ('<h4 class="filter-title">Mục tiêu lối sống</h4>', '<h4 class="filter-title">Lifestyle Goals</h4>'),
        ('<span>Tập Gym / Tăng cơ</span>', '<span>Gym / Muscle Gain</span>'),
        ('<span>Giảm cân</span>', '<span>Weight Loss</span>'),
        ('<span>Bổ sung năng lượng</span>', '<span>Energy Boost</span>'),
        ('<span>Dinh dưỡng gia đình</span>', '<span>Family Nutrition</span>'),
        ('<span>Ăn vặt lành mạnh</span>', '<span>Healthy Snacking</span>'),
        ('<h4 class="filter-title">Khoảng giá</h4>', '<h4 class="filter-title">Price Range</h4>'),
        ('<span>Tất cả</span>', '<span>All Prices</span>'),
        ('<span>Dưới 50.000đ</span>', '<span>Under 50,000đ</span>'),
        ('<span>50.000đ - 100.000đ</span>', '<span>50,000đ - 100,000đ</span>'),
        ('<span>100.000đ - 200.000đ</span>', '<span>100,000đ - 200,000đ</span>'),
        ('<span>Trên 200.000đ</span>', '<span>Over 200,000đ</span>'),
        ('<h4 class="filter-title">Loại sản phẩm</h4>', '<h4 class="filter-title">Product Categories</h4>'),
        ('<span>Trái cây theo mùa</span>', '<span>Seasonal Fruits</span>'),
        ('<span>Hạt dinh dưỡng</span>', '<span>Nutritional Seeds</span>'),
        ('<h4 class="filter-title">Ưu đãi</h4>', '<h4 class="filter-title">Offers</h4>'),
        ('<span>Bán chạy</span>', '<span>Bestsellers</span>'),
        ('<span>Đang giảm giá</span>', '<span>On Sale</span>'),
        ('<span>Sản phẩm theo mùa</span>', '<span>Seasonal Products</span>'),
        ('Đặt lại bộ lọc', 'Reset Filters'),
        ('Lọc & Tìm', 'Filter & Search'),
        ('Hiển thị <strong id="product-count">0</strong> sản phẩm', 'Showing <strong id="product-count">0</strong> products'),
        ('<label for="sort-select">Sắp xếp theo:</label>', '<label for="sort-select">Sort by:</label>'),
        ('<option value="newest">Mới nhất</option>', '<option value="newest">Newest</option>'),
        ('<option value="price-asc">Giá thấp đến cao</option>', '<option value="price-asc">Price: Low to High</option>'),
        ('<option value="price-desc">Giá cao đến thấp</option>', '<option value="price-desc">Price: High to Low</option>'),
        ('<option value="bestseller">Bán chạy nhất</option>', '<option value="bestseller">Best Sellers</option>'),
        ('<span>Kết quả tìm kiếm cho: "<strong><span id="search-keyword-vi"></span><span id="search-keyword-en"></span></strong>"</span>',
         '<span>Search results for: "<strong><span id="search-keyword-vi"></span><span id="search-keyword-en"></span></strong>"</span>'),
        ('<h3>Không tìm thấy sản phẩm nào</h3>', '<h3>No products found</h3>'),
        ('<p>Chúng tôi không tìm thấy kết quả phù hợp với các tiêu chí lọc của bạn. Vui lòng thử lại hoặc đặt lại bộ lọc.</p>',
         '<p>We could not find any products matching your filters. Please try again or reset filters.</p>'),
        ('<button id="reset-empty-btn" class="btn btn-primary">Xem tất cả sản phẩm</button>',
         '<button id="reset-empty-btn" class="btn btn-primary">Show all products</button>'),
        ('Tứ Quý Garden cam kết mang đến nông sản hữu cơ theo mùa tươi ngon, hạt dinh dưỡng chọn lọc và granola lành mạnh chăm sóc sức khỏe gia đình bạn mỗi ngày.',
         'Tứ Quý Garden commits to bringing ripe seasonal organic produce, premium seeds, and clean healthy granola to nourish your family daily.'),
        ('<h3 class="footer-title">Danh mục</h3>', '<h3 class="footer-title">Categories</h3>'),
        ('<li><a href="products.html?category=Fruits">Trái cây theo mùa</a></li>', '<li><a href="products.html?category=Fruits">Seasonal Fruits</a></li>'),
        ('<li><a href="products.html?category=Nutritional Seeds">Hạt dinh dưỡng</a></li>', '<li><a href="products.html?category=Nutritional Seeds">Nutritional Seeds</a></li>'),
        ('<li><a href="products.html?category=Granola">Granola ngũ cốc</a></li>', '<li><a href="products.html?category=Granola">Cereal Granola</a></li>'),
        ('<li><a href="products.html?category=Combo Healthy">Combo sống khỏe</a></li>', '<li><a href="products.html?category=Combo Healthy">Healthy Combo</a></li>'),
        ('<li><a href="nutrition.html">Dinh dưỡng cá nhân</a></li>', '<li><a href="nutrition.html">Personalized Nutrition</a></li>'),
        ('<li><a href="traceability.html">Tra cứu nguồn gốc</a></li>', '<li><a href="traceability.html">Trace Origin</a></li>'),
        ('<h3 class="footer-title">Hỗ trợ khách hàng</h3>', '<h3 class="footer-title">Customer Support</h3>'),
        ('<li><a href="about.html">Giới thiệu cửa hàng</a></li>', '<li><a href="about.html">About Store</a></li>'),
        ('<li><a href="about.html">Chính sách đổi trả</a></li>', '<li><a href="about.html">Return Policy</a></li>'),
        ('<li><a href="about.html">Chính sách giao hàng</a></li>', '<li><a href="about.html">Shipping Policy</a></li>'),
        ('<li><a href="about.html">Câu hỏi thường gặp</a></li>', '<li><a href="about.html">FAQs</a></li>'),
        ('<h3 class="footer-title">Kết nối với chúng tôi</h3>', '<h3 class="footer-title">Connect With Us</h3>'),
        ('<p class="newsletter-txt">Đăng ký để nhận ưu đãi:</p>', '<p class="newsletter-txt">Subscribe for offers:</p>'),
        ('<a href="about.html">Điều khoản sử dụng</a>', '<a href="about.html">Terms of Use</a>'),
        ('<a href="about.html">Chính sách bảo mật</a>', '<a href="about.html">Privacy Policy</a>')
    ],
    'profile.html': [
        ('content: "Thêm vào giỏ";', 'content: "Add to Cart";'),
        ('title: "Đổi ảnh đại diện"', 'title: "Change Avatar"'),
        ('title: "Xóa ảnh đại diện"', 'title: "Remove Avatar"'),
        ('aria-label="Gỡ ảnh đại diện"', 'aria-label="Remove Avatar"'),
        ('Khách hàng thân thiết', 'Loyal Customer'),
        ('title="Xem chi tiết điểm thưởng"', 'title="View reward points details"'),
        ('<span>Điểm thưởng hiện có</span>', '<span>Current Reward Points</span>'),
        ('<span>1.250 điểm</span>', '<span>1,250 points</span>'),
        ('<p class="progress-text">Chi tiêu thêm 750 điểm để lên hạng Vàng</p>', '<p class="progress-text">Earn 750 points more to reach Gold status</p>'),
        ('<h3 class="info-card-title">Thông tin tài khoản</h3>', '<h3 class="info-card-title">Account Information</h3>'),
        ('<p class="info-card-subtitle">Quản lý thông tin cá nhân và mục tiêu sức khỏe của bạn.</p>', 
         '<p class="info-card-subtitle">Manage your personal details and wellness goals.</p>'),
        ('<span>Chỉnh sửa</span>', '<span>Edit</span>'),
        ('<label class="field-label">Họ và tên</label>', '<label class="field-label">Full Name</label>'),
        ('placeholder="Nguyễn Văn A"', 'placeholder="John Doe"'),
        ('<span class="email-helper-text" id="email-helper-text">🔐 Thay đổi email cần xác minh mã OTP</span>',
         '<span class="email-helper-text" id="email-helper-text">🔐 Changing email requires OTP verification</span>'),
        ('<label class="field-label">Số điện thoại</label>', '<label class="field-label">Phone Number</label>'),
        ('<label class="field-label">Mục tiêu sức khỏe</label>', '<label class="field-label">Health Goal</label>'),
        ('<option value="Tăng cơ">Tăng cơ / Gym</option>', '<option value="Tăng cơ">Gym / Muscle Gain</option>'),
        ('<option value="Giảm cân">Giảm cân</option>', '<option value="Giảm cân">Weight Loss</option>'),
        ('<option value="Mẹ bầu">Mẹ bầu & Bé</option>', '<option value="Mẹ bầu">Mother & Baby</option>'),
        ('<option value="Gia đình">Sức khỏe Gia đình</option>', '<option value="Gia đình">Family Health</option>'),
        ('<button type="button" class="btn-cancel-edit" onclick="cancelEditMode()">Hủy</button>',
         '<button type="button" class="btn-cancel-edit" onclick="cancelEditMode()">Cancel</button>'),
        ('<button type="submit" class="btn-save-edit">Lưu thay đổi</button>',
         '<button type="submit" class="btn-save-edit">Save Changes</button>'),
        ('<span>Thông tin của bạn được bảo mật và chỉ sử dụng để nâng cao trải nghiệm mua sắm.</span>',
         '<span>Your details are secure and only used to personalize your experience.</span>'),
        ('<h4 class="health-title">Hồ sơ sức khỏe</h4>', '<h4 class="health-title">Wellness Profile</h4>'),
        ('<h5 class="health-section-title">Mục tiêu hiện tại</h5>', '<h5 class="health-section-title">Current Goal</h5>'),
        ('<h5 class="health-section-title">Ưu tiên</h5>', '<h5 class="health-section-title">Priorities</h5>'),
        ('<p class="health-text">Ít đường, giàu chất xơ, trái cây tươi</p>', '<p class="health-text">Low sugar, high fiber, organic fresh fruits</p>'),
        ('<h5 class="health-section-title">Gợi ý dành cho bạn</h5>', '<h5 class="health-section-title">Recommendations for You</h5>'),
        ('<span>Cập nhật mục tiêu</span>', '<span>Update Goals</span>'),
        ('<h3 class="info-card-title">Lịch sử đơn hàng</h3>', '<h3 class="info-card-title">Order History</h3>'),
        ('<p class="info-card-subtitle">Theo dõi trạng thái và quản lý đơn hàng của bạn.</p>', 
         '<p class="info-card-subtitle">Track status and manage your order history.</p>'),
        ('<button class="filter-chip active" id="chip-filter-All" onclick="filterOrdersByStatus(\'Tất cả\')">Tất cả</button>',
         '<button class="filter-chip active" id="chip-filter-All" onclick="filterOrdersByStatus(\'Tất cả\')">All</button>'),
        ('<button class="filter-chip" id="chip-filter-Pending" onclick="filterOrdersByStatus(\'Chờ xác nhận\')">Chờ xác nhận</button>',
         '<button class="filter-chip" id="chip-filter-Pending" onclick="filterOrdersByStatus(\'Chờ xác nhận\')">Pending</button>'),
        ('<button class="filter-chip" id="chip-filter-Shipping" onclick="filterOrdersByStatus(\'Đang giao\')">Đang giao</button>',
         '<button class="filter-chip" id="chip-filter-Shipping" onclick="filterOrdersByStatus(\'Đang giao\')">Shipping</button>'),
        ('<button class="filter-chip" id="chip-filter-Completed" onclick="filterOrdersByStatus(\'Hoàn thành\')">Hoàn thành</button>',
         '<button class="filter-chip" id="chip-filter-Completed" onclick="filterOrdersByStatus(\'Hoàn thành\')">Completed</button>'),
        ('<button class="filter-chip" id="chip-filter-Cancelled" onclick="filterOrdersByStatus(\'Đã hủy\')">Đã hủy</button>',
         '<button class="filter-chip" id="chip-filter-Cancelled" onclick="filterOrdersByStatus(\'Đã hủy\')">Cancelled</button>'),
        ('title="Xóa tìm kiếm"', 'title="Clear Search"'),
        ('<span class="summary-label">Tổng đơn hàng</span>', '<span class="summary-label">Total Orders</span>'),
        ('<span class="summary-label">Chờ xác nhận</span>', '<span class="summary-label">Pending</span>'),
        ('<span class="summary-label">Đang giao</span>', '<span class="summary-label">Shipping</span>'),
        ('<span class="summary-label">Hoàn thành</span>', '<span class="summary-label">Completed</span>'),
        ('<h3 class="info-card-title">Sản phẩm yêu thích</h3>', '<h3 class="info-card-title">Wishlist</h3>'),
        ('<p class="info-card-subtitle">Lưu lại những sản phẩm bạn quan tâm để mua nhanh hơn.</p>', 
         '<p class="info-card-subtitle">Save products you love for easy shopping later.</p>'),
        ('<span class="wishlist-count-badge" id="wishlist-count-badge">0 sản phẩm yêu thích</span>',
         '<span class="wishlist-count-badge" id="wishlist-count-badge">0 products in wishlist</span>'),
        ('<option value="newest">Sắp xếp: Mới thêm</option>', '<option value="newest">Sort: Recently Added</option>'),
        ('<option value="price-asc">Giá: Thấp đến Cao</option>', '<option value="price-asc">Price: Low to High</option>'),
        ('<option value="price-desc">Giá: Cao đến Thấp</option>', '<option value="price-desc">Price: High to Low</option>'),
        ('<h3 class="profile-modal-title" id="email-otp-title">Xác nhận đổi email</h3>',
         '<h3 class="profile-modal-title" id="email-otp-title">Confirm Email Change</h3>'),
        ('<p class="profile-modal-subtitle">Nhập mã OTP đã được gửi đến email mới để xác nhận thay đổi.</p>',
         '<p class="profile-modal-subtitle">Enter the OTP sent to your new email to confirm details.</p>'),
        ('<div class="otp-error-msg" id="email-otp-error">Mã xác nhận không đúng</div>',
         '<div class="otp-error-msg" id="email-otp-error">Invalid verification code</div>'),
        ('<div class="otp-demo-hint">Mã OTP demo: 123456</div>', '<div class="otp-demo-hint">Demo OTP code: 123456</div>'),
        ('<button type="button" class="btn-otp-cancel" onclick="closeEmailOtpModal()">Hủy</button>',
         '<button type="button" class="btn-otp-cancel" onclick="closeEmailOtpModal()">Cancel</button>'),
        ('<button type="button" class="btn-otp-submit" onclick="confirmEmailOtp()">Xác nhận</button>',
         '<button type="button" class="btn-otp-submit" onclick="confirmEmailOtp()">Confirm</button>')
    ],
    'nutrition.html': [
        ('<div style="font-size:13px; font-weight:600;" id="bmi-category">Bình thường</div>',
         '<div style="font-size:13px; font-weight:600;" id="bmi-category">Normal</div>'),
        ('<h3 style="font-size:18px; color:var(--color-text-dark); margin-bottom:15px;" id="rec-title">Sinh Tố Xoài Bơ Hạt Dinh Dưỡng</h3>',
         '<h3 style="font-size:18px; color:var(--color-text-dark); margin-bottom:15px;" id="rec-title">Avocado Mango Nut Smoothie</h3>'),
        ('<p style="font-size:14px; line-height:1.6; color:var(--color-text-light); margin-bottom:15px;" id="rec-desc">Công thức phối chế này cung cấp nguồn năng lượng lành mạnh từ bơ sáp béo ngậy kết hợp vị ngọt thanh của xoài cát và vi chất dinh dưỡng của các loại hạt cao cấp.</p>',
         '<p style="font-size:14px; line-height:1.6; color:var(--color-text-light); margin-bottom:15px;" id="rec-desc">This formulation provides a healthy energy source from rich buttery avocado combined with the sweet taste of Hoa Loc mango and premium nuts micronutrients.</p>')
    ],
    'traceability.html': [
        ('<option value="TQG-XOAI-001">#TQG-XOAI-001 (Xoài cát Hòa Lộc)</option>', '<option value="TQG-XOAI-001">#TQG-XOAI-001 (Hoa Loc Mango)</option>'),
        ('<option value="TQG-MAN-002">#TQG-MAN-002 (Mận hậu Bản Ôn)</option>', '<option value="TQG-MAN-002">#TQG-MAN-002 (Ban On Plum)</option>'),
        ('<option value="TQG-BUOI-003">#TQG-BUOI-003 (Bưởi da xanh)</option>', '<option value="TQG-BUOI-003">#TQG-BUOI-003 (Green Skin Pomelo)</option>'),
        ('<option value="TQG-HAT-004">#TQG-HAT-004 (Hạt Dinh Dưỡng Mix)</option>', '<option value="TQG-HAT-004">#TQG-HAT-004 (Nutritional Seeds Mix)</option>'),
        ('<option value="TQG-CHIA-005">#TQG-CHIA-005 (Hạt chia hữu cơ)</option>', '<option value="TQG-CHIA-005">#TQG-CHIA-005 (Organic Chia Seeds)</option>'),
        ('<option value="TQG-ROI-006">#TQG-ROI-006 (Roi An Phước Cái Bè)</option>', '<option value="TQG-ROI-006">#TQG-ROI-006 (Cai Be Bell Fruit)</option>'),
        ('placeholder="Ví dụ: TQG-XOAI-001 hoặc mã đơn hàng..."', 'placeholder="e.g., TQG-XOAI-001 or order ID..."'),
        ('<text x="50" y="80" text-anchor="middle" font-size="7" fill="#666">Chờ chọn sản phẩm</text>',
         '<text x="50" y="80" text-anchor="middle" font-size="7" fill="#666">Waiting for product selection</text>'),
        ('<option value="">-- Chọn sản phẩm giả lập --</option>', '<option value="">-- Choose Demo Product --</option>'),
        ('<option value="TQG-XOAI-001">Xoài cát Hòa Lộc (Cái Bè, Tiền Giang)</option>', '<option value="TQG-XOAI-001">Hoa Loc Mango (Cai Be, Tien Giang)</option>'),
        ('<option value="TQG-MAN-002">Mận hậu Bản Ôn (Mộc Châu, Sơn La)</option>', '<option value="TQG-MAN-002">Ban On Plum (Moc Chau, Son La)</option>'),
        ('<option value="TQG-BUOI-003">Bưởi da xanh (Mỏ Cày Bắc, Bến Tre)</option>', '<option value="TQG-BUOI-003">Green Skin Pomelo (Mo Cay Bac, Ben Tre)</option>'),
        ('<option value="TQG-HAT-004">Mix hạt dinh dưỡng (Krông Năng, Đắk Lắk)</option>', '<option value="TQG-HAT-004">Nutritional Seeds Mix (Krong Nang, Dak Lak)</option>'),
        ('<option value="TQG-CHIA-005">Hạt chia hữu cơ (Nhập khẩu Úc)</option>', '<option value="TQG-CHIA-005">Organic Chia Seeds (Imported from Australia)</option>'),
        ('<option value="TQG-ROI-006">Roi An Phước đỏ ngọt (Cái Bè, Tiền Giang)</option>', '<option value="TQG-ROI-006">Sweet An Phuoc Bell Fruit (Cai Be, Tien Giang)</option>'),
        ('<h2 id="result-product-name" style="font-size: 26px; color: var(--color-text-dark); margin-bottom: 8px;">Xoài cát Hòa Lộc sạch Cái Bè</h2>',
         '<h2 id="result-product-name" style="font-size: 26px; color: var(--color-text-dark); margin-bottom: 8px;">Cai Be Organic Hoa Loc Mango</h2>'),
        ('<p id="result-batch-code" style="color: var(--color-primary); font-weight:700; font-size:16px; margin-bottom: 15px;">Mã lô: #TQG-XOAI-001</p>',
         '<p id="result-batch-code" style="color: var(--color-primary); font-weight:700; font-size:16px; margin-bottom: 15px;">Batch Code: #TQG-XOAI-001</p>'),
        ('<p id="result-product-desc" style="font-size: 14px; line-height: 1.6; color: var(--color-text-light);">Xoài chín cây thơm lừng, thu hoạch trực tiếp tại Hợp tác xã Song Thuận, huyện Cái Bè, tỉnh Tiền Giang. Đạt tiêu chuẩn VietGAP xuất khẩu.</p>',
         '<p id="result-product-desc" style="font-size: 14px; line-height: 1.6; color: var(--color-text-light);">Fully tree-ripened mango, harvested directly at Song Thuan Cooperative, Cai Be district, Tien Giang province. Certified VietGAP for export.</p>'),
        ('<span id="result-coop">HTX Xoài cát Cái Bè, Tiền Giang</span>', '<span id="result-coop">Cai Be Mango Cooperative, Tien Giang</span>'),
        ('<span id="result-farmer">Bác Hai Chân</span>', '<span id="result-farmer">Mr. Hai Chan (Farmer)</span>'),
        ('<span class="cert-badge-item">Chỉ dẫn địa lý</span>', '<span class="cert-badge-item">Geographical Indication</span>')
    ]
}

for filepath, subs in files_to_translate.items():
    if os.path.exists(filepath):
        print(f"Translating remaining items in {filepath}...")
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        original = content
        for src, dest in subs:
            content = content.replace(src, dest)
            
        if content != original:
            with open(filepath, 'w', encoding='utf-8') as f:
                f.write(content)
            print(f"Updated {filepath}")
        else:
            print(f"No changes in {filepath}")

print("Page translations finished!")
