import os

js_files = ['js/checkout.js', 'js/cart.js', 'js/chatbot.js']

checkout_subs = [
    ('let placedDeliveryText = "Dự kiến 2-3 ngày";', 'let placedDeliveryText = "Expected 2-3 days";'),
    ('title: "Miễn phí vận chuyển", description: "Áp dụng mọi đơn hàng", condition: "Không yêu cầu giá trị tối thiểu"', 
     'title: "Free Shipping", description: "Applies to all orders", condition: "No minimum order required"'),
    ('title: "Giảm 10%", description: "Tối đa 100.000đ", condition: "Áp dụng mọi đơn hàng"', 
     'title: "10% Off", description: "Up to 100,000đ", condition: "Applies to all orders"'),
    ('title: "Giảm 50.000đ", description: "Cho đơn từ 500.000đ", condition: "Đơn hàng từ 500.000đ"', 
     'title: "50,000đ Off", description: "For orders from 500,000đ", condition: "Min order 500,000đ"'),
    
    ('title: "Giao tiêu chuẩn", desc: "Dự kiến giao trong 2-3 ngày", price: 0, priceText: "Freeship", tag: "Khuyến nghị"',
     'title: "Standard Shipping", desc: "Estimated delivery in 2-3 days", price: 0, priceText: "Free", tag: "Recommended"'),
    ('title: "Giao nhanh", desc: "Dự kiến giao trong 24h-48h"',
     'title: "Express Shipping", desc: "Estimated delivery in 24h-48h"'),
    ('title: "Giao hẹn giờ", desc: "Chọn khung giờ mong muốn"',
     'title: "Scheduled Delivery", desc: "Choose your preferred time slot"'),
    
    ('title: "Thanh toán khi nhận hàng (COD)", desc: "Thanh toán cho shipper khi nhận hàng"',
     'title: "Cash on Delivery (COD)", desc: "Pay the shipper upon receiving items"'),
    ('title: "Ví điện tử MoMo / ZaloPay", desc: "Chức năng thanh toán demo cho đồ án"',
     'title: "E-Wallet (MoMo / ZaloPay)", desc: "Demo payment feature for project"'),
    ('title: "Chuyển khoản ngân hàng", desc: "Chuyển khoản theo thông tin tài khoản demo"',
     'title: "Bank Transfer", desc: "Transfer according to the demo bank details"'),
    ('title: "Thẻ ATM / Visa (Demo)", desc: "Chức năng thanh toán demo cho đồ án"',
     'title: "ATM / Visa Card (Demo)", desc: "Demo payment feature for project"'),
    
    ('fullName: "Nguyễn Hoàng Anh"', 'fullName: "Nguyen Hoang Anh"'),
    ('province: "TP. Hồ Chí Minh"', 'province: "TP. Ho Chi Minh"'),
    ('district: "Thành Phố Thủ Đức"', 'district: "Thu Duc City"'),
    ('ward: "Phường Linh Trung"', 'ward: "Linh Trung Ward"'),
    ('address: "Cổng Sau Ktx Đhqg, Khu B Đhqg"', 'address: "VNU-HCM Dormitory Zone B"'),
    
    ('{ code: "79", name: "Thành phố Hồ Chí Minh" }', '{ code: "79", name: "Ho Chi Minh City" }'),
    ('{ code: "01", name: "Thành phố Hà Nội" }', '{ code: "01", name: "Hanoi City" }'),
    ('{ code: "48", name: "Thành phố Đà Nẵng" }', '{ code: "48", name: "Da Nang City" }'),
    
    ('{ code: "26734", name: "Phường Linh Trung", provinceCode: "79" }', '{ code: "26734", name: "Linh Trung Ward", provinceCode: "79" }'),
    ('{ code: "26737", name: "Phường Thủ Đức", provinceCode: "79" }', '{ code: "26737", name: "Thu Duc Ward", provinceCode: "79" }'),
    ('{ code: "00001", name: "Phường Ba Đình", provinceCode: "01" }', '{ code: "00001", name: "Ba Dinh Ward", provinceCode: "01" }'),
    ('{ code: "20194", name: "Phường Hải Châu", provinceCode: "48" }', '{ code: "20194", name: "Hai Chau Ward", provinceCode: "48" }'),
    
    ('locationData.error = "Không thể tải dữ liệu địa phương";', 'locationData.error = "Could not load local address data";'),
    ('<span>Đặt hàng ngay</span>', '<span>Place Order</span>'),
    ('Chúng tôi cam kết bảo mật thông tin của bạn và không chia sẻ cho bên thứ ba.', 'We protect your data and do not share it with third parties.'),
    ('Giỏ hàng của bạn đang trống', 'Your cart is empty'),
    ('Không có sản phẩm nào để thanh toán. Vui lòng quay lại mua sắm.', 'There are no products to check out. Please return to shopping.'),
    ('Quay lại cửa hàng', 'Return to Store'),
    ('Thông tin nhận hàng', 'Shipping Address'),
    ('Ghi chú: ', 'Note: '),
    ('Thay đổi', 'Change'),
    ('Phương thức giao hàng', 'Shipping Method'),
    ('Khung giờ giao hàng', 'Preferred Delivery Time'),
    ('Phương thức thanh toán', 'Payment Method'),
    ('Thu gọn', 'Collapse'),
    ('Xem thêm phương thức thanh toán', 'Show more payment methods'),
    ('Bạn chưa liên kết tài khoản ngân hàng', 'You have not linked a bank account'),
    ('Liên kết tài khoản ngân hàng để dùng phương thức chuyển khoản.', 'Link a bank account to use bank transfer.'),
    ('Liên kết ngân hàng', 'Link Bank'),
    ('Ngân hàng đã liên kết', 'Linked Bank Account'),
    ('Thông tin chuyển khoản sẽ được lưu kèm đơn hàng demo.', 'Bank transfer details will be saved with the demo order.'),
    ('Chọn ngân hàng', 'Select Bank'),
    ('Chủ tài khoản: ', 'Account Holder: '),
    ('Số tài khoản: ', 'Account Number: '),
    ('Nội dung: ', 'Memo: '),
    
    ('Điểm thưởng & Hóa đơn', 'Reward Points & Invoice'),
    ('Bạn hiện có: <strong>1.250 điểm</strong>', 'You currently have: <strong>1,250 points</strong>'),
    ('Dùng 500 điểm để giảm 50.000đ', 'Use 500 points for a 50,000đ discount'),
    ('Sau khi dùng, bạn còn 750 điểm', 'After using, you will have 750 points left'),
    ('Tôi muốn xuất hóa đơn', 'I want to request an invoice'),
    ('Hóa đơn điện tử sẽ được gửi qua email của bạn', 'Electronic invoice will be sent to your email'),
    ('Tên công ty', 'Company Name'),
    ('Mã số thuế', 'Tax Code'),
    ('Email nhận hóa đơn', 'Invoice Email'),
    
    ('Đơn hàng của bạn', 'Your Order'),
    ('Nhập mã voucher', 'Enter voucher code'),
    ('Áp dụng', 'Apply'),
    ('Xem voucher có thể dùng', 'View available vouchers'),
    ('Chi tiết thanh toán', 'Payment Details'),
    ('Tạm tính', 'Subtotal'),
    ('Phí giao hàng', 'Shipping Fee'),
    ('Giảm giá voucher', 'Voucher Discount'),
    ('Giảm phí vận chuyển', 'Shipping Discount'),
    ('Giảm giá điểm thưởng', 'Reward Points Discount'),
    ('Đóng gói quà', 'Gift Wrapping'),
    ('Thiệp chúc mừng', 'Greeting Card'),
    ('Tổng thanh toán', 'Total cost'),
    ('Bạn tiết kiệm: ', 'You save: '),
    ('Bạn sẽ nhận được: ', 'You will earn: '),
    ('Thanh toán an toàn', 'Secure Checkout'),
    ('Hỗ trợ 24/7', '24/7 Support'),
    ('Đổi trả dễ dàng', 'Easy Returns'),
    ('7 ngày', '7 Days'),
    ('Thông tin của bạn được bảo mật tuyệt đối', 'Your information is fully secured'),
    
    ('Thay đổi thông tin người nhận', 'Change Recipient Info'),
    ('Thêm người nhận khác', 'Add recipient'),
    ('Xong', 'Done'),
    ('Sửa', 'Edit'),
    ('Họ và tên người nhận', 'Recipient Name'),
    ('Số điện thoại', 'Phone Number'),
    ('Địa chỉ chi tiết', 'Detailed Address'),
    ('Ghi chú đơn hàng', 'Order Note'),
    ('Gọi trước khi giao', 'Call before delivery'),
    ('Đặt làm địa chỉ mặc định', 'Set as default address'),
    ('Quay lại', 'Back'),
    ('Lưu địa chỉ', 'Save Address'),
    
    ('Đang tải dữ liệu địa phương...', 'Loading local database...'),
    ('Chọn Tỉnh/Thành phố', 'Select Province/City'),
    ('Tỉnh/Thành phố', 'Province/City'),
    ('Vui lòng chọn Tỉnh/Thành phố trước', 'Please select a Province/City first'),
    ('Chọn Phường/Xã', 'Select Ward/Commune'),
    ('Không có dữ liệu Phường/Xã', 'No Ward data available'),
    ('Phường/Xã', 'Ward/Commune'),
    
    ('Xác nhận vị trí giao hàng', 'Confirm Delivery Location'),
    ('Ghim vị trí giúp shipper giao hàng chính xác hơn.', 'Pin your location to help shipper deliver accurately.'),
    ('Sử dụng vị trí hiện tại của bạn', 'Use current location'),
    ('Tọa độ giao hàng: ', 'Delivery coordinates: '),
    ('Click vào bản đồ để ghim vị trí giao hàng.', 'Click on map to pin delivery location.'),
    ('Không thể tải bản đồ. Vui lòng kiểm tra kết nối mạng hoặc nhập địa chỉ thủ công.', 
     'Failed to load map. Please check your connection or enter address manually.'),
    ('Trình duyệt của bạn không hỗ trợ lấy vị trí hiện tại.', 'Your browser does not support geolocation.'),
    ('Đang lấy vị trí...', 'Fetching position...'),
    ('Đã lấy vị trí hiện tại. Vui lòng kiểm tra lại ghim trên bản đồ.', 
     'Current position fetched. Please check the pin on the map.'),
    ('Bạn đã từ chối quyền truy cập vị trí. Vui lòng nhập địa chỉ thủ công.', 
     'Location access denied. Please enter address manually.'),
    ('Không thể lấy vị trí hiện tại. Vui lòng thử lại hoặc ghim thủ công trên bản đồ.', 
     'Could not fetch current location. Please try again or pin manually.'),
    
    ('Họ tên không được trống', 'Name cannot be empty'),
    ('Số điện thoại không hợp lệ', 'Invalid phone number'),
    ('Email không đúng định dạng', 'Invalid email address'),
    ('Vui lòng chọn Tỉnh/Thành phố', 'Please select a Province/City'),
    ('Vui lòng chọn Phường/Xã', 'Please select a Ward/Commune'),
    ('Địa chỉ chi tiết không được trống', 'Detailed address cannot be empty'),
    ('Bạn chưa ghim vị trí trên bản đồ. Shipper có thể cần gọi để xác nhận địa chỉ.', 
     'You have not pinned your location. Shipper might call to confirm.'),
    
    ('Đã cập nhật thông tin nhận hàng', 'Recipient info updated'),
    ('Chọn phương thức giao hàng', 'Select Shipping Method'),
    ('Hủy', 'Cancel'),
    ('Lưu phương thức', 'Save Method'),
    ('Đã cập nhật phương thức giao hàng', 'Shipping method updated'),
    ('Chọn phương thức thanh toán', 'Select Payment Method'),
    ('Đã cập nhật phương thức thanh toán', 'Payment method updated'),
    ('Đã áp dụng mã ', 'Applied code '),
    ('Vui lòng nhập mã voucher', 'Please enter a voucher code'),
    ('Mã voucher không hợp lệ', 'Invalid voucher code'),
    ('Đơn hàng chưa đủ điều kiện áp dụng voucher', 'Order is not eligible for this voucher'),
    ('Đã xoá voucher', 'Voucher removed'),
    
    ('Liên kết ngân hàng demo', 'Link Demo Bank Account'),
    ('Tên ngân hàng', 'Bank Name'),
    ('Đặt làm ngân hàng mặc định', 'Set as default bank'),
    ('Lưu ngân hàng', 'Save Bank'),
    ('Vui lòng nhập tên ngân hàng', 'Please enter bank name'),
    ('Vui lòng nhập chủ tài khoản', 'Please enter account holder name'),
    ('Số tài khoản cần từ 6 đến 20 chữ số', 'Account number must be 6 to 20 digits'),
    ('Đã liên kết ngân hàng demo', 'Demo bank linked successfully'),
    ('Đã áp dụng điểm thưởng', 'Reward points applied'),
    
    ('Vui lòng nhập tên người nhận.', 'Please enter recipient name.'),
    ('Số điện thoại nhận hàng không hợp lệ.', 'Invalid recipient phone number.'),
    ('Email người nhận không đúng định dạng.', 'Invalid recipient email.'),
    ('Vui lòng nhập địa chỉ chi tiết.', 'Please enter detailed address.'),
    ('Vui lòng bổ sung phường/xã và tỉnh/thành.', 'Please select province/city and ward/commune.'),
    ('Vui lòng chọn phương thức giao hàng.', 'Please select shipping method.'),
    ('Vui lòng chọn khung giờ giao hàng.', 'Please select shipping time slot.'),
    ('Vui lòng chọn phương thức thanh toán.', 'Please select payment method.'),
    ('Vui lòng liên kết tài khoản ngân hàng để chuyển khoản.', 'Please link a bank account for bank transfer.'),
    ('Vui lòng chọn ngân hàng chuyển khoản.', 'Please select bank for transfer.'),
    ('Vui lòng nhập tên công ty để xuất hóa đơn.', 'Please enter company name for invoice.'),
    ('Vui lòng nhập mã số thuế.', 'Please enter tax code.'),
    ('Email nhận hóa đơn không hợp lệ.', 'Invalid invoice email.'),
    
    ('Xác nhận đặt hàng', 'Confirm Order'),
    ('Địa chỉ giao hàng', 'Delivery Address'),
    ('Đã lấy vị trí hiện tại. Vui lòng kiểm tra lại ghim trên bản đồ.', 'Current position fetched. Please check the pin on the map.'),
    ('Đặt hàng thành công', 'Order Placed Successfully'),
    ('Cảm ơn bạn đã lựa chọn Tứ Quý Garden. Đơn hàng đang chờ xác nhận.', 
     'Thank you for choosing Tứ Quý Garden. Your order is pending confirmation.'),
    ('Mã đơn', 'Order ID'),
    ('Dự kiến giao hàng', 'Expected Delivery'),
    ('Xem đơn hàng', 'View Orders'),
    ('Tiếp tục mua sắm', 'Continue Shopping'),
    ('Chờ xác nhận', 'Pending')
]

cart_subs = [
    ('title: "Miễn phí vận chuyển", description: "Áp dụng cho mọi đơn hàng", condition: "Không yêu cầu giá trị tối thiểu"',
     'title: "Free Shipping", description: "Applies to all orders", condition: "No minimum order required"'),
    ('title: "Giảm 10%", description: "Tối đa 50.000đ", condition: "Áp dụng cho mọi đơn hàng"',
     'title: "10% Discount", description: "Max 50,000đ", condition: "Applies to all orders"'),
    ('title: "Giảm 50.000đ", description: "Cho đơn từ 500.000đ", condition: "Đơn hàng từ 500.000đ"',
     'title: "50,000đ Discount", description: "For orders from 500,000đ", condition: "Orders from 500,000đ"'),
    
    ('"Fruits": "Trái cây tươi ngon"', '"Fruits": "Fresh Fruits"'),
    ('"Nutritional Seeds": "Hạt dinh dưỡng"', '"Nutritional Seeds": "Nutritional Seeds"'),
    ('"Granola": "Granola ngũ cốc"', '"Granola": "Granola"'),
    ('"Combo Healthy": "Combo sống khỏe"', '"Combo Healthy": "Combo Healthy"'),
    
    ('? "Chúc mừng! Các sản phẩm đã chọn được <strong>Miễn phí vận chuyển toàn quốc</strong>!"',
     '? "Congratulations! Selected items are eligible for <strong>Free nationwide shipping</strong>!"'),
    (': `Bạn cần chọn mua thêm <strong>${formatCurrency(progress.needed)}</strong> nữa để được Freeship toàn quốc.`}',
     ': `Buy <strong>${formatCurrency(progress.needed)}</strong> more to get Free shipping nationwide.`}'),
    
    ('<span>${selectedCount}/${cartItems.length} sản phẩm</span>', '<span>${selectedCount}/${cartItems.length} products</span>'),
    ('Vui lòng chọn ít nhất một sản phẩm để thanh toán', 'Please select at least one product to checkout'),
    ('clearCart()"><span class="lang-vi">Xóa sạch giỏ hàng</span>', 'clearCart()"><span class="lang-vi">Xóa sạch giỏ hàng</span><span class="lang-en">Clear Cart</span>'),
    ('btn.textContent = action.label || "Hoàn tác";', 'btn.textContent = action.label || "Undo";'),
    ('return { success: false, message: `Mã ${voucher.code} cần đơn hàng đã chọn từ ${formatCurrency(voucher.minOrder)}.` };',
     'return { success: false, message: `Voucher ${voucher.code} requires a minimum order of ${formatCurrency(voucher.minOrder)}.` };'),
    ('showCartToast(`Đã xóa ${product ? product.name : "sản phẩm"} khỏi giỏ hàng`, "success", {',
     'showCartToast(`Removed ${product ? product.name : "product"} from cart`, "success", {'),
    ('label: "Hoàn tác",', 'label: "Undo",'),
    ('if (confirm("Xóa toàn bộ giỏ hàng?")) {', 'if (confirm("Clear the entire cart?")) {'),
    ('showCartToast("Đã xóa sạch giỏ hàng.", "success");', 'showCartToast("Cart cleared successfully.", "success");'),
    ('showCartToast("Vui lòng nhập mã.", "error");', 'showCartToast("Please enter code.", "error");'),
    ('showCartToast(`Đã áp dụng mã ${formattedCode}`, "success");', 'showCartToast(`Code ${formattedCode} applied successfully`, "success");'),
    ('showCartToast("Đã gỡ mã giảm giá.", "success");', 'showCartToast("Promo code removed.", "success");'),
    ('showCartToast("Vui lòng chọn ít nhất một sản phẩm để thanh toán", "error");', 'showCartToast("Please select at least one product to checkout", "error");')
]

chatbot_subs = [
    ('season: "mùa Tết và đầu năm"', 'season: "Tet and New Year season"'),
    ('season: "mùa sau Tết"', 'season: "after Tet season"'),
    ('season: "mùa xuân"', 'season: "Spring season"'),
    ('season: "đầu mùa hè"', 'season: "early Summer season"'),
    ('season: "mùa hè"', 'season: "Summer season"'),
    ('season: "mùa trái cây nhiệt đới"', 'season: "tropical fruits season"'),
    ('season: "cuối mùa hè"', 'season: "late Summer season"'),
    ('season: "đầu mùa thu"', 'season: "early Autumn season"'),
    ('season: "mùa thu"', 'season: "Autumn season"'),
    ('season: "cuối thu đầu đông"', 'season: "late Autumn early Winter season"'),
    ('season: "mùa cuối năm"', 'season: "end of year season"'),
    
    ('"Mùa này trái cây gì?"', '"What fruits are in season?"'),
    ('"Gợi ý combo eat clean"', '"Suggest eat clean combo"'),
    ('"Sản phẩm cho người tập gym"', '"Products for gym-goers"'),
    ('"Truy xuất nguồn gốc là gì?"', '"What is traceability?"'),
    ('"Chính sách giao hàng"', '"Delivery policy"'),
    ('"Hỗ trợ checkout"', '"Checkout support"'),
    
    (': "Với mục tiêu eat clean hoặc kiểm soát cân nặng, bạn có thể chọn Granola ít đường, hạt chia, hạnh nhân, Seasonal Fruit Box và Eat Clean Box. Những sản phẩm này phù hợp cho bữa sáng, snack văn phòng hoặc bữa phụ lành mạnh."',
     ': "For eat clean or weight control goals, you can choose low-sugar Granola, chia seeds, almonds, Seasonal Fruit Box, and Eat Clean Box. These products are perfect for a healthy breakfast, office snacks, or side meals."'),
    (': "Với người tập gym, mình gợi ý Gym Starter Box, Mix Nuts 5 loại, hạt điều rang mộc, granola và trái cây giàu năng lượng như chuối, xoài hoặc bơ. Đây là nhóm sản phẩm phù hợp cho bữa phụ trước hoặc sau tập."',
     ': "For gym-goers, I recommend Gym Starter Box, Mix Nuts 5 types, wood-roasted cashews, granola, and energy-rich fruits like banana, mango, or avocado. Great for pre- or post-workout snacks."'),
    (': "QR traceability giúp khách hàng kiểm tra thông tin sản phẩm như vùng trồng, ngày thu hoạch, nhà cung cấp, batch code, cách bảo quản và chứng nhận nếu có. Điều này giúp việc mua trái cây online minh bạch và đáng tin hơn."',
     ': "QR traceability helps customers verify product info such as farm origin, harvest date, supplier, batch code, storage, and certs. This makes online shopping transparent and trustworthy."'),
    (': "Tứ Quý Garden ưu tiên giao tươi trong ngày tại khu vực nội thành và đóng gói cẩn thận để giữ chất lượng sản phẩm. Một số khu vực xa hơn có thể phụ thuộc vào thời gian vận chuyển và loại sản phẩm."',
     ': "Tứ Quý Garden prioritizes same-day fresh delivery in inner-city areas and packs carefully. Outer areas may depend on transport time."'),
    (': "Bạn có thể thêm sản phẩm vào giỏ hàng, kiểm tra số lượng, nhập thông tin nhận hàng và xác nhận đơn tại trang checkout. Nếu chưa chắc nên chọn gì, mình có thể gợi ý combo phù hợp trước khi bạn đặt hàng."',
     ': "You can add items to cart, check quantities, enter recipient info, and confirm at checkout. Ask me if you need help choosing combos!"'),
    (': "Các thông tin như VietGAP, HACCP hoặc ISO được hiển thị khi có hồ sơ xác thực từ nhà cung cấp. Trong bản prototype, các badge chứng nhận được dùng để minh họa chức năng minh bạch thông tin."',
     ': "Certifications like VietGAP, HACCP, or ISO are displayed when verified by suppliers. In this prototype, badges are used to illustrate transparency features."'),
    (': `Tại vùng trồng Cái Bè, Tiền Giang, nhiệt độ hiện tại là ${w.temp}°C (${w.descVi}).`',
     ': `At Cái Bè farm, Tiền Giang, the current temperature is ${w.temp}°C (${w.descEn}).`'),
    (': "Hiện tại mình chưa cập nhật được thời tiết chính xác tại vườn Cái Bè, nhưng thông thường ở đây thời tiết nắng ấm mát mẻ!"',
     ': "I can\'t fetch the exact weather at Cái Bè farm right now, but it\'s usually warm and sunny here!"'),
    (': "Bạn có thể bắt đầu với trái cây theo mùa, Granola hạt & trái cây hoặc Mix Nuts 5 loại. Nếu mua cho gia đình, mình gợi ý Seasonal Fruit Box. Nếu mua cho lối sống lành mạnh, bạn có thể chọn Eat Clean Box hoặc Combo Healthy."',
     ': "Start with seasonal fruits, Granola, or Mix Nuts 5 types. For families, try Seasonal Fruit Box. For healthy lifestyle, choose Eat Clean Box or Healthy Combo."'),
    (': "Mình chưa chắc câu hỏi này. Bạn có thể hỏi mình về trái cây theo mùa, combo healthy, granola, hạt dinh dưỡng, truy xuất nguồn gốc, giao hàng hoặc checkout."',
     ': "I\'m not sure about that. Try asking me about seasonal fruits, healthy combos, granola, nuts, traceability, shipping, or checkout."'),
    (': "Xin chào! Mình là trợ lý của Tứ Quý Garden. Mình có thể giúp bạn chọn trái cây theo mùa, gợi ý combo healthy, giải thích truy xuất nguồn gốc và hỗ trợ đặt hàng."',
     ': "Hi! I\'m Tứ Quý Garden\'s assistant. I can help you choose seasonal fruits, recommend healthy combos, explain traceability, and support your shopping journey."'),
    (': "Đã kích hoạt trí tuệ nhân tạo Gemini! Hãy hỏi bất kỳ câu hỏi nào để bắt đầu trò chuyện thông minh."',
     ': "Gemini AI activated! Ask any questions to start chatting intelligently."'),
    ('appendMessage("bot", isEn ? "Gemini deactivated. Reverting to rule-based mode." : "Đã tắt Gemini. Quay lại chế độ khớp từ khóa.");',
     'appendMessage("bot", "Gemini deactivated. Reverting to rule-based mode.");'),
    
    ('? `Khách hàng đang có mục tiêu sức khỏe: "${userGoal}". Hãy ưu tiên giới thiệu sản phẩm phù hợp với mục tiêu này.`',
     '? `The customer\'s active health goal is: "${userGoal}". Please prioritize recommending products that align with this goal.`'),
    
    ('text: `SYSTEM INSTRUCTION:\\nBạn là Trợ lý ảo AI thông minh của cửa hàng Tứ Quý Garden. Hãy trò chuyện thân thiện bằng tiếng Việt (hoặc tiếng Anh nếu khách hỏi bằng tiếng Anh). Dưới đây là danh sách sản phẩm thực tế của cửa hàng:\\n${catalog}\\n\\nThời tiết tại Cái Bè hiện tại: ${weather}. ${goalInstruction}\\n\\nYêu cầu câu trả lời:\\n1. Giải đáp thắc mắc, khuyên dùng sản phẩm phù hợp thời tiết hoặc nhu cầu sức khỏe của khách.\\n2. Khi giới thiệu sản phẩm, hãy nhắc chính xác Tên Sản Phẩm để hệ thống tự động quét và hiện thẻ mua hàng phía dưới.\\n3. Trả lời cực kỳ ngắn gọn (không quá 3 câu, khoảng 40-60 từ) để vừa vặn khung chat di động.\\n\\nUSER QUESTION:\\n${trimmed}`',
     'text: `SYSTEM INSTRUCTION:\\nYou are the smart AI Assistant of Tứ Quý Garden store. Chat friendly in English. Below is the actual catalog of products:\\n${catalog}\\n\\nWeather at Cái Bè farm: ${weather}. ${goalInstruction}\\n\\nResponse requirements:\\n1. Answer queries, recommend products suited for the weather or health goals.\\n2. When recommending products, use the exact Product Name so the system can display buying cards below.\\n3. Reply extremely briefly (no more than 3 sentences, 40-60 words) to fit the mobile chat view.\\n\\nUSER QUESTION:\\n${trimmed}`'),
    
    (': " Dựa trên mục tiêu tập luyện/gym của bạn, mình gợi ý dùng các dòng hạt dinh dưỡng bồi bổ năng lượng và protein nhé!";',
     ': " Based on your gym goals, I recommend our premium nutritional seeds to boost your energy and protein intake!";'),
    (': " Phù hợp với chế độ ăn Eat Clean và kiểm soát cân nặng của bạn, đây là các dòng hạt chia và combo lành mạnh của cửa hàng.";',
     ': " Perfect for your Eat Clean and weight control goals, I recommend our chia seeds and healthy combos.";'),
    
    (': ` (Lưu ý: Thời tiết Cái Bè hiện tại đang khá nắng nóng ${window.currentWeather.temp}°C, bạn nên ưu tiên dùng các dòng quả tươi giải nhiệt nhé!)`;',
     ': ` (Note: The weather in Cái Bè is currently hot at ${window.currentWeather.temp}°C, so cooling fresh fruits are highly recommended!)`;'),
    (': ` (Lưu ý: Thời tiết hiện đang có mưa mát mẻ, rất thích hợp nhâm nhi hũ Granola sấy giòn béo ngậy!)`;',
     ': ` (Note: It is rainy and cool now, perfect to enjoy a crunchy and rich jar of baked Granola!)`;'),
    
    (': "Nhập Google Gemini API Key để kích hoạt trí tuệ nhân tạo (để trống để xóa):"',
     ': "Enter Google Gemini API Key to activate AI (leave empty to disable):"'),
    ('alert(isEnglish() ? "Gemini API Key activated!" : "Đã kích hoạt Gemini API Key thành công!");',
     'alert("Gemini API Key activated!");'),
    ('alert(isEnglish() ? "Gemini deactivated." : "Đã tắt chế độ AI thông minh.");',
     'alert("Gemini deactivated.");')
]

def apply_subs(filepath, subs):
    print(f"Translating {filepath}...")
    with open(filepath, 'r', encoding='utf-8') as f:
        content = f.read()
    
    original = content
    for src, dest in subs:
        content = content.replace(src, dest)
        
    if content != original:
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
        print(f"Updated {filepath}")
    else:
        print(f"No changes in {filepath}")

apply_subs('js/checkout.js', checkout_subs)
apply_subs('js/cart.js', cart_subs)
apply_subs('js/chatbot.js', chatbot_subs)
print("JavaScript translations complete!")
