import os

admin_js_path = 'js/admin.js'

admin_subs = [
    ('window.showToast("Đăng xuất quản trị viên thành công.", "success");', 'window.showToast("Logged out successfully.", "success");'),
    ('window.showConfirmModal("Bạn có chắc chắn muốn khôi phục toàn bộ Dữ liệu gốc sản phẩm và đơn hàng mẫu?", () => {', 
     'window.showConfirmModal("Are you sure you want to restore all original product and order mockup data?", () => {'),
    ('window.showToast("Đã khôi phục dữ liệu gốc thành công!", "success");', 'window.showToast("Restored original data successfully!", "success");'),
    ('bestBody.innerHTML = `<tr><td colspan="2" style="text-align:center; color:var(--color-text-light);">Chưa có dữ liệu</td></tr>`;', 
     'bestBody.innerHTML = `<tr><td colspan="2" style="text-align:center; color:var(--color-text-light);">No data available</td></tr>`;'),
    ('recentBody.innerHTML = `<tr><td colspan="4" style="text-align:center; color:var(--color-text-light);">Chưa có đơn hàng nào</td></tr>`;', 
     'recentBody.innerHTML = `<tr><td colspan="4" style="text-align:center; color:var(--color-text-light);">No orders yet</td></tr>`;'),
    ('lowBody.innerHTML = `<tr><td colspan="4" style="text-align:center; color:var(--color-success); font-weight:600; padding:15px 0;">Mọi sản phẩm đều có tồn kho an toàn!</td></tr>`;', 
     'lowBody.innerHTML = `<tr><td colspan="4" style="text-align:center; color:var(--color-success); font-weight:600; padding:15px 0;">All products have safe stock levels!</td></tr>`;'),
    ('window.showToast("Tính năng đang được phát triển nâng cấp!", "info");', 'window.showToast("Feature under development!", "info");'),
    
    ('<h3 style="font-size:18px; margin-bottom:20px; border-bottom:1px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-primary);">Thêm sản phẩm mới</h3>',
     '<h3 style="font-size:18px; margin-bottom:20px; border-bottom:1px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-primary);">Add New Product</h3>'),
    ('<label>Tên sản phẩm (Tiếng Việt) *</label>', '<label>Product Name (Vietnamese) *</label>'),
    ('placeholder="Ví dụ: Dưa lưới Huỳnh Long"', 'placeholder="e.g., Huynh Long Cantaloupe"'),
    ('<label>Tên sản phẩm (Tiếng Anh) *</label>', '<label>Product Name (English) *</label>'),
    ('<label>Danh mục *</label>', '<label>Category *</label>'),
    ('<option value="Fruits">Trái cây tươi</option>', '<option value="Fruits">Fresh Fruits</option>'),
    ('<option value="Nutritional Seeds">Hạt dinh dưỡng</option>', '<option value="Nutritional Seeds">Nutritional Seeds</option>'),
    ('<option value="Granola">Granola ngũ cốc</option>', '<option value="Granola">Granola</option>'),
    ('<option value="Combo Healthy">Combo sống khỏe</option>', '<option value="Combo Healthy">Combo Healthy</option>'),
    ('<label>Vùng trồng / Xuất xứ *</label>', '<label>Origin / Region *</label>'),
    ('placeholder="Đồng Tháp"', 'placeholder="e.g., Dong Thap"'),
    ('<label>Đơn giá (VND) *</label>', '<label>Price (VND) *</label>'),
    ('<label>Giá cũ (Không bắt buộc)</label>', '<label>Old Price (Optional)</label>'),
    ('<label>Số lượng tồn kho *</label>', '<label>Stock Qty *</label>'),
    ('<label>Đường dẫn hình ảnh *</label>', '<label>Image File Path *</label>'),
    ('<span>Sản phẩm theo mùa</span>', '<span>Seasonal Product</span>'),
    ('<span>Sản phẩm bán chạy (Bestseller)</span>', '<span>Bestseller Product</span>'),
    ('<label>Mô tả chi tiết sản phẩm *</label>', '<label>Detailed Description *</label>'),
    ('placeholder="Dưa lưới Huỳnh Long trồng công nghệ cao, cơm vàng giòn, ngọt thanh..."', 
     'placeholder="Huynh Long Cantaloupe grown with high technology, crispy gold flesh, sweet taste..."'),
    ('<button type="button" class="btn btn-outline" onclick="window.closeCustomModal()">Hủy</button>',
     '<button type="button" class="btn btn-outline" onclick="window.closeCustomModal()">Cancel</button>'),
    ('<button type="submit" class="btn btn-primary">Lưu sản phẩm</button>',
     '<button type="submit" class="btn btn-primary">Save Product</button>'),
    
    ('storageVi: "Bảo quản ngăn mát tủ lạnh từ 4°C - 8°C.",', 'storageVi: "Store in refrigerator cooler from 4°C - 8°C.",'),
    ('window.showToast("Đã thêm sản phẩm mới thành công!", "success");', 'window.showToast("Product added successfully!", "success");'),
    
    ('<h3 style="font-size:18px; margin-bottom:20px; border-bottom:1px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-primary);">Chỉnh sửa thông tin sản phẩm #${p.id}</h3>',
     '<h3 style="font-size:18px; margin-bottom:20px; border-bottom:1px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-primary);">Edit Product Details #${p.id}</h3>'),
    ('<option value="Fruits" ${p.category === "Fruits" ? "selected" : ""}>Trái cây tươi</option>',
     '<option value="Fruits" ${p.category === "Fruits" ? "selected" : ""}>Fresh Fruits</option>'),
    ('<option value="Nutritional Seeds" ${p.category === "Nutritional Seeds" ? "selected" : ""}>Hạt dinh dưỡng</option>',
     '<option value="Nutritional Seeds" ${p.category === "Nutritional Seeds" ? "selected" : ""}>Nutritional Seeds</option>'),
    ('<option value="Granola" ${p.category === "Granola" ? "selected" : ""}>Granola ngũ cốc</option>',
     '<option value="Granola" ${p.category === "Granola" ? "selected" : ""}>Granola</option>'),
    ('<option value="Combo Healthy" ${p.category === "Combo Healthy" ? "selected" : ""}>Combo sống khỏe</option>',
     '<option value="Combo Healthy" ${p.category === "Combo Healthy" ? "selected" : ""}>Combo Healthy</option>'),
    ('<button type="submit" class="btn btn-primary">Cập nhật sản phẩm</button>',
     '<button type="submit" class="btn btn-primary">Update Product</button>'),
    
    ('window.showToast("Cập nhật thông tin sản phẩm thành công!", "success");', 'window.showToast("Product updated successfully!", "success");'),
    ('window.showConfirmModal(`Bạn có chắc chắn muốn xóa sản phẩm "${p.name}"? Hành động này không thể khôi phục.`, () => {',
     'window.showConfirmModal(`Are you sure you want to delete product "${p.name}"? This action cannot be undone.`, () => {'),
    ('window.showToast("Đã xóa sản phẩm khỏi kho hàng.", "success");', 'window.showToast("Product removed from catalog.", "success");'),
    
    ('<strong>Người nhận:</strong> ${o.customerName}<br>', '<strong>Recipient:</strong> ${o.customerName}<br>'),
    ('<strong>Điện thoại:</strong> ${o.customerPhone}<br>', '<strong>Phone:</strong> ${o.customerPhone}<br>'),
    ('<strong>Email:</strong> ${o.customerEmail || \'Trống\'}<br>', '<strong>Email:</strong> ${o.customerEmail || \'Empty\'}<br>'),
    ('<strong>Địa chỉ:</strong> ${o.address}', '<strong>Address:</strong> ${o.address}'),
    
    ('<h4 style="margin:0 0 10px 0; font-size:13px; color:#2E3A2B; font-weight: 800; border-bottom:1px solid rgba(77, 124, 47, 0.1); padding-bottom:6px;">Thông tin giao nhận</h4>',
     '<h4 style="margin:0 0 10px 0; font-size:13px; color:#2E3A2B; font-weight: 800; border-bottom:1px solid rgba(77, 124, 47, 0.1); padding-bottom:6px;">Recipient Details</h4>'),
    ('<h4 style="margin:0 0 10px 0; font-size:13px; color:#2E3A2B; font-weight: 800; border-bottom:1px solid rgba(244, 185, 66, 0.15); padding-bottom:6px;">Chi tiết thanh toán</h4>',
     '<h4 style="margin:0 0 10px 0; font-size:13px; color:#2E3A2B; font-weight: 800; border-bottom:1px solid rgba(244, 185, 66, 0.15); padding-bottom:6px;">Payment Details</h4>'),
    ('<strong>Phương thức:</strong> 💵 ${translatePaymentMethod(o.paymentMethod)}<br>', '<strong>Method:</strong> 💵 ${translatePaymentMethod(o.paymentMethod)}<br>'),
    ('<strong>Trạng thái ĐH:</strong> <span style="font-weight:700; color:#4D7C2F;">${o.status}</span><br>', 
     '<strong>Status:</strong> <span style="font-weight:700; color:#4D7C2F;">${o.status}</span><br>'),
    ('<strong>Ghi chú đơn:</strong> <span style="font-style: italic; color: #5B6A56;">"${o.note || \'Không có ghi chú\'}"</span>',
     '<strong>Notes:</strong> <span style="font-style: italic; color: #5B6A56;">"${o.note || \'No notes\'}"</span>'),
    ('<h4 style="margin:0 0 10px 0; font-size:14px; color:#2E3A2B; font-weight: 800; border-bottom:1px solid #E2DDD5; padding-bottom:6px;">Sản phẩm đặt hàng</h4>',
     '<h4 style="margin:0 0 10px 0; font-size:14px; color:#2E3A2B; font-weight: 800; border-bottom:1px solid #E2DDD5; padding-bottom:6px;">Ordered Products</h4>'),
    
    ('<span>Tạm tính:</span>', '<span>Subtotal:</span>'),
    ('<span>Phí giao hàng:</span>', '<span>Shipping:</span>'),
    ('<span>Giảm giá:</span>', '<span>Discount:</span>'),
    ('<span>Tổng thanh toán:</span>', '<span>Total payment:</span>'),
    ('<button class="btn btn-primary" onclick="window.closeCustomModal()" style="border-radius: 8px; font-size: 13.5px; font-weight: 700; padding: 8px 20px;">Đóng cửa sổ</button>',
     '<button class="btn btn-primary" onclick="window.closeCustomModal()" style="border-radius: 8px; font-size: 13.5px; font-weight: 700; padding: 8px 20px;">Close Window</button>'),
    
    ('<span>🌐 Tất cả</span>', '<span>🌐 All Regions</span>'),
    ('<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">📦 Phân tích Kho Sản Phẩm</h2>',
     '<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">📦 Inventory Analysis</h2>'),
    ('<span style="font-size:11.5px; color:var(--color-text-light); display:block; margin-bottom:6px; font-weight:700;">TỔNG SẢN PHẨM</span>',
     '<span style="font-size:11.5px; color:var(--color-text-light); display:block; margin-bottom:6px; font-weight:700;">TOTAL PRODUCTS</span>'),
    ('<span style="font-size:11.5px; color:#c2410c; display:block; margin-bottom:6px; font-weight:700;">HẾT HÀNG / THẤP</span>',
     '<span style="font-size:11.5px; color:#c2410c; display:block; margin-bottom:6px; font-weight:700;">OUT OF STOCK / LOW</span>'),
    ('<span style="font-size:11.5px; color:#15803d; display:block; margin-bottom:6px; font-weight:700;">TỔNG GIÁ TRỊ KHO</span>',
     '<span style="font-size:11.5px; color:#15803d; display:block; margin-bottom:6px; font-weight:700;">TOTAL WAREHOUSE VALUE</span>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; border-bottom:2px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-text-dark);">Phân bổ Danh mục</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; border-bottom:2px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-text-dark);">Category Distribution</h3>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; border-bottom:2px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-text-dark);">Danh sách nhanh</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; border-bottom:2px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-text-dark);">Inventory Quicklist</h3>'),
    ('<th style="padding:12px 14px; text-align:center;">Ảnh</th>', '<th style="padding:12px 14px; text-align:center;">Image</th>'),
    ('<th style="padding:12px 14px;">Tên sản vật</th>', '<th style="padding:12px 14px;">Product Name</th>'),
    ('<th style="padding:12px 14px;">Loại</th>', '<th style="padding:12px 14px;">Type</th>'),
    ('<th style="padding:12px 14px;">Giá bán</th>', '<th style="padding:12px 14px;">Price</th>'),
    ('<th style="padding:12px 14px; text-align:center;">Tồn kho</th>', '<th style="padding:12px 14px; text-align:center;">Stock</th>'),
    
    ('deleteAdminCustomer(\'${u.id}\')" style="background:#fee2e2; color:#ef4444; border:none; padding:6px 12px; border-radius:6px; font-size:12px; cursor:pointer; font-weight:bold;">Xóa</button>',
     'deleteAdminCustomer(\'${u.id}\')" style="background:#fee2e2; color:#ef4444; border:none; padding:6px 12px; border-radius:6px; font-size:12px; cursor:pointer; font-weight:bold;">Delete</button>'),
    ('<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">👤 Quản lý Khách hàng</h2>',
     '<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">👤 Customers Management</h2>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Danh sách tài khoản khách hàng</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Customer Accounts List</h3>'),
    ('<th style="padding:12px 16px;">Họ tên</th>', '<th style="padding:12px 16px;">Full Name</th>'),
    ('<th style="padding:12px 16px;">SĐT</th>', '<th style="padding:12px 16px;">Phone</th>'),
    ('<th style="padding:12px 16px;">Mục tiêu sức khỏe</th>', '<th style="padding:12px 16px;">Health Goal</th>'),
    ('<th style="padding:12px 16px; text-align:center;">Hành động</th>', '<th style="padding:12px 16px; text-align:center;">Actions</th>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Thêm khách hàng mới</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Add New Customer</h3>'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">HỌ TÊN</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">FULL NAME</label>'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">SỐ ĐIỆN THOẠI</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">PHONE NUMBER</label>'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">MẬT KHẨU</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">PASSWORD</label>'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">MỤC TIÊU SỨC KHỎE</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">HEALTH GOAL</label>'),
    ('<option value="Eat Clean">Eat Clean (Ăn sạch sống khỏe)</option>', '<option value="Eat Clean">Eat Clean (Healthy eating)</option>'),
    ('<option value="Giảm cân">Giảm cân giữ dáng</option>', '<option value="Giảm cân">Weight loss</option>'),
    ('<option value="Tăng cơ">Tăng cơ bắp thể thao</option>', '<option value="Tăng cơ">Gym / Muscle gain</option>'),
    ('<option value="Snack lành mạnh">Snack lành mạnh</option>', '<option value="Snack lành mạnh">Healthy snacking</option>'),
    ('<button type="submit" class="btn btn-primary" style="font-size:13px; font-weight: 700; padding:10px 24px; border-radius:8px;">Thêm Tài Khoản</button>',
     '<button type="submit" class="btn btn-primary" style="font-size:13px; font-weight: 700; padding:10px 24px; border-radius:8px;">Add Account</button>'),
    
    ('window.showToast("Tạo khách hàng mới thành công!", "success");', 'window.showToast("New customer created successfully!", "success");'),
    ('window.showConfirmModal("Bạn có chắc chắn muốn xóa tài khoản khách hàng này khỏi hệ thống?", () => {',
     'window.showConfirmModal("Are you sure you want to delete this customer account?", () => {'),
    ('window.showToast("Đã xóa tài khoản khách hàng thành công!", "success");', 'window.showToast("Customer account deleted successfully!", "success");'),
    
    ('<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">📁 Quản lý Danh mục</h2>',
     '<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">📁 Category Management</h2>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Danh mục sản phẩm hiện có</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Product Categories</h3>'),
    ('<th style="padding:12px 16px;">Tên Danh mục</th>', '<th style="padding:12px 16px;">Category Name</th>'),
    ('<th style="padding:12px 16px; text-align:center;">Số lượng sản phẩm liên kết</th>', '<th style="padding:12px 16px; text-align:center;">Linked Products Count</th>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Thêm danh mục sản phẩm mới</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Add New Category</h3>'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">TÊN DANH MỤC MỚI</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">NEW CATEGORY NAME</label>'),
    ('placeholder="Ví dụ: Combo Quà Tặng, Trái Cây Sấy Khô..."', 'placeholder="e.g., Gift Combo, Dried Fruits..."'),
    ('<button type="submit" class="btn btn-primary" style="font-size:13px; font-weight:700; padding:10px 24px; border-radius:8px; height: 42px;">Tạo Danh Mục</button>',
     '<button type="submit" class="btn btn-primary" style="font-size:13px; font-weight:700; padding:10px 24px; border-radius:8px; height: 42px;">Create Category</button>'),
    
    ('window.showToast("Danh mục này đã tồn tại!", "warning");', 'window.showToast("Category already exists!", "warning");'),
    ('window.showToast(`Đã tạo danh mục "${name}" thành công!`, "success");', 'window.showToast(`Category "${name}" created successfully!`, "success");'),
    ('window.showConfirmModal(`Bạn có chắc chắn muốn xóa danh mục "${catName}"?`, () => {',
     'window.showConfirmModal(`Are you sure you want to delete category "${catName}"?`, () => {'),
    ('window.showToast(`Đã xóa danh mục "${catName}"!`, "success");', 'window.showToast(`Category "${catName}" deleted!`, "success");'),
    
    ('<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">🏷️ Quản lý Mã Giảm Giá</h2>',
     '<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">🏷️ Promo Codes Management</h2>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Mã giảm giá đang hoạt động</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Active Vouchers</h3>'),
    ('<th style="padding:12px 16px;">Mã Code</th>', '<th style="padding:12px 16px;">Promo Code</th>'),
    ('<th style="padding:12px 16px;">Loại / Giá trị</th>', '<th style="padding:12px 16px;">Type / Value</th>'),
    ('<th style="padding:12px 16px;">Đơn tối thiểu</th>', '<th style="padding:12px 16px;">Min Order</th>'),
    ('<th style="padding:12px 16px;">Mô tả chi tiết</th>', '<th style="padding:12px 16px;">Description</th>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Tạo chương trình khuyến mãi mới</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark);">Create New Promotion</h3>'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">MÃ CODE GIẢM GIÁ (Viết liền hoa)</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">PROMO CODE (Uppercase)</label>'),
    ('placeholder="Ví dụ: TUQUYHE30"', 'placeholder="e.g., TUQUYHE30"'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">LOẠI GIẢM GIÁ</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">DISCOUNT TYPE</label>'),
    ('<option value="percentage">Giảm theo Phần trăm (%)</option>', '<option value="percentage">Percentage (%)</option>'),
    ('<option value="fixed">Giảm theo Số tiền cố định (đ)</option>', '<option value="fixed">Fixed Amount (đ)</option>'),
    ('<option value="freeship">Miễn phí vận chuyển (Freeship)</option>', '<option value="freeship">Free Shipping</option>'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">GIÁ TRỊ GIẢM (% hoặc đ)</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">DISCOUNT VALUE (% or đ)</label>'),
    ('placeholder="Ví dụ: 10 hoặc 30000"', 'placeholder="e.g., 10 or 30000"'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">ĐƠN HÀNG TỐI THIỂU YÊU CẦU</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">MINIMUM REQUIRED ORDER</label>'),
    ('placeholder="Ví dụ: 200000"', 'placeholder="e.g., 200000"'),
    ('<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">MÔ TẢ CHI TIẾT HIỂN THỊ</label>',
     '<label style="font-size:12px; font-weight:700; display:block; margin-bottom:6px; color:var(--color-text-dark);">DISPLAY DESCRIPTION</label>'),
    ('placeholder="Ví dụ: Giảm ngay 30K cho đơn hàng rau quả từ 200K..."', 'placeholder="e.g., Get 30K off for fruit orders from 200K..."'),
    ('<button type="submit" class="btn btn-primary" style="font-size:13px; font-weight:700; padding:10px 24px; border-radius:8px;">Tạo Khuyến Mãi</button>',
     '<button type="submit" class="btn btn-primary" style="font-size:13px; font-weight:700; padding:10px 24px; border-radius:8px;">Create Promotion</button>'),
    
    ('window.showToast("Mã này thuộc mã hệ thống mặc định, không thể ghi đè!", "warning");', 
     'window.showToast("This is a system default voucher code, cannot be overwritten!", "warning");'),
    ('window.showToast(`Đã lưu mã giảm giá "${code}" thành công!`, "success");', 'window.showToast(`Voucher code "${code}" saved successfully!`, "success");'),
    ('window.showConfirmModal(`Bạn có chắc chắn muốn xóa mã giảm giá "${code}"?`, () => {',
     'window.showConfirmModal(`Are you sure you want to delete voucher code "${code}"?`, () => {'),
    ('window.showToast(`Đã xóa mã giảm giá "${code}"!`, "success");', 'window.showToast(`Voucher code "${code}" deleted!`, "success");'),
    
    ('<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">📈 Báo cáo Giao dịch & Phân tích</h2>',
     '<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">📈 Transactions & Analytics Report</h2>'),
    ('<span style="font-size:11.5px; color:#15803d; display:block; margin-bottom:6px; font-weight:700;">DOANH THU THỰC TẾ</span>',
     '<span style="font-size:11.5px; color:#15803d; display:block; margin-bottom:6px; font-weight:700;">ACTUAL REVENUE</span>'),
    ('<span style="font-size:11.5px; color:#b45309; display:block; margin-bottom:6px; font-weight:700;">ĐƠN HÀNG THÀNH CÔNG</span>',
     '<span style="font-size:11.5px; color:#b45309; display:block; margin-bottom:6px; font-weight:700;">COMPLETED ORDERS</span>'),
    ('<span style="font-size:11.5px; color:#b91c1c; display:block; margin-bottom:6px; font-weight:700;">TỶ LỆ HỦY ĐƠN HÀNG</span>',
     '<span style="font-size:11.5px; color:#b91c1c; display:block; margin-bottom:6px; font-weight:700;">ORDER CANCEL RATE</span>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; border-bottom:2px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-text-dark);">Doanh thu theo Nhóm sản vật</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; border-bottom:2px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-text-dark);">Revenue by Category</h3>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; border-bottom:2px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-text-dark);">Top 3 Khách hàng chi tiêu tốt nhất</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; border-bottom:2px solid var(--color-gray-border); padding-bottom:8px; color:var(--color-text-dark);">Top 3 Best Spending Customers</h3>'),
    ('<span id="report-details-title">Chi tiết sản phẩm bán chạy</span>', '<span id="report-details-title">Bestselling Products Details</span>'),
    ('<th style="padding:12px 14px;">Sản phẩm sản vật</th>', '<th style="padding:12px 14px;">Product Name</th>'),
    ('<th style="padding:12px 14px; text-align:center;">Số lượng đã bán</th>', '<th style="padding:12px 14px; text-align:center;">Quantity Sold</th>'),
    ('<th style="padding:12px 14px; text-align:right;">Doanh thu thu về</th>', '<th style="padding:12px 14px; text-align:right;">Revenue Earned</th>'),
    
    ('tbody.innerHTML = `<tr><td colspan="3" style="text-align:center; padding:15px; color:var(--color-text-light);">Không có sản phẩm nào thuộc nhóm này được bán.</td></tr>`;',
     'tbody.innerHTML = `<tr><td colspan="3" style="text-align:center; padding:15px; color:var(--color-text-light);">No products sold in this category yet.</td></tr>`;'),
    
    ('<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">⚙️ Cài đặt hệ thống quản trị</h2>',
     '<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">⚙️ System Management Settings</h2>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark); border-bottom:2px solid var(--color-gray-border); padding-bottom:8px;">Giao diện và Ngôn ngữ</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark); border-bottom:2px solid var(--color-gray-border); padding-bottom:8px;">Theme & Language</h3>'),
    ('<strong style="color:var(--color-text-dark); font-size:14.5px;">Chế độ tối (Dark Mode)</strong>',
     '<strong style="color:var(--color-text-dark); font-size:14.5px;">Dark Mode</strong>'),
    ('<span style="font-size:12px; color:var(--color-text-light); display:block; margin-top:2px;">Đổi giao diện sang tông màu trầm tự nhiên bảo vệ mắt khi làm việc ban đêm</span>',
     '<span style="font-size:12px; color:var(--color-text-light); display:block; margin-top:2px;">Switch interface to dark colors to protect eyes when working at night</span>'),
    ('<strong style="color:var(--color-text-dark); font-size:14.5px;">Ngôn ngữ hiển thị (Bilingual Language)</strong>',
     '<strong style="color:var(--color-text-dark); font-size:14.5px;">Display Language</strong>'),
    ('<span style="font-size:12px; color:var(--color-text-light); display:block; margin-top:2px;">Chuyển đổi ngôn ngữ hiển thị chính giữa Tiếng Việt và English</span>',
     '<span style="font-size:12px; color:var(--color-text-light); display:block; margin-top:2px;">Switch main interface language between Vietnamese and English</span>'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark); border-bottom:2px solid var(--color-gray-border); padding-bottom:8px;">Bảo mật tài khoản</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:var(--color-text-dark); border-bottom:2px solid var(--color-gray-border); padding-bottom:8px;">Account Security</h3>'),
    ('<strong style="color:var(--color-text-dark); font-size:14.5px;">Đổi mật khẩu đăng nhập</strong>',
     '<strong style="color:var(--color-text-dark); font-size:14.5px;">Change Password</strong>'),
    ('<span style="font-size:12px; color:var(--color-text-light); display:block; margin-top:2px;">Thay đổi mật khẩu đăng nhập hệ thống quản trị của bạn</span>',
     '<span style="font-size:12px; color:var(--color-text-light); display:block; margin-top:2px;">Change your administrator login password</span>'),
    ('🔑 Đổi Mật Khẩu', '🔑 Change Password'),
    ('<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:#b91c1c; border-bottom:2px solid rgba(185,28,28,0.1); padding-bottom:8px;">Hành động hệ thống nâng cao</h3>',
     '<h3 style="margin:0 0 15px 0; font-size:16px; font-weight:800; color:#b91c1c; border-bottom:2px solid rgba(185,28,28,0.1); padding-bottom:8px;">Advanced System Actions</h3>'),
    ('<strong style="color:#b91c1c; font-size:14.5px;">Khôi phục dữ liệu mẫu mặc định</strong>',
     '<strong style="color:#b91c1c; font-size:14.5px;">Restore Default Database Mockup</strong>'),
    ('<span style="font-size:12px; color:#7f1d1d; display:block; margin-top:2px;">Xóa các thay đổi cục bộ của bạn để khôi phục cơ sở dữ liệu về trạng thái ban đầu</span>',
     '<span style="font-size:12px; color:#7f1d1d; display:block; margin-top:2px;">Clear local changes and restore database mockup to original state</span>'),
    ('🔄 Khôi Phục DB', '🔄 Restore DB'),
    
    ('window.showToast("Đã thay đổi ngôn ngữ hiển thị hệ thống!", "success");', 'window.showToast("Display language updated!", "success");'),
    ('window.showToast("Đã xóa bộ nhớ đệm và khôi phục dữ liệu!", "success");', 'window.showToast("Cache cleared and database restored!", "success");'),
    ('window.showToast(`Đã lọc dữ liệu kinh doanh theo ngày: ${formatted}`, "success");', 'window.showToast(`Business stats filtered by date: ${formatted}`, "success");'),
    ('window.showToast("Ảnh quá lớn! Vui lòng chọn ảnh dưới 1.5MB.", "warning");', 'window.showToast("Image too large! Please choose an image under 1.5MB.", "warning");'),
    ('window.showToast("Đã thay đổi ảnh đại diện Admin thành công!", "success");', 'window.showToast("Admin avatar updated successfully!", "success");'),
    
    ('<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">🔑 Đổi mật khẩu tài khoản quản trị</h2>',
     '<h2 style="font-size:24px; font-weight: 800; color:#4D7C2F; margin: 0;">🔑 Change Admin Password</h2>'),
    ('<label style="display:block; margin-bottom:8px; font-weight:700; color:var(--color-text-dark);">Mật khẩu hiện tại *</label>',
     '<label style="display:block; margin-bottom:8px; font-weight:700; color:var(--color-text-dark);">Current Password *</label>'),
    ('placeholder="Nhập mật khẩu hiện tại"', 'placeholder="Enter current password"'),
    ('<label style="display:block; margin-bottom:8px; font-weight:700; color:var(--color-text-dark);">Mật khẩu mới *</label>',
     '<label style="display:block; margin-bottom:8px; font-weight:700; color:var(--color-text-dark);">New Password *</label>'),
    ('placeholder="Nhập mật khẩu mới (tối thiểu 6 ký tự)"', 'placeholder="Enter new password (min 6 characters)"'),
    ('<label style="display:block; margin-bottom:8px; font-weight:700; color:var(--color-text-dark);">Xác nhận mật khẩu mới *</label>',
     '<label style="display:block; margin-bottom:8px; font-weight:700; color:var(--color-text-dark);">Confirm New Password *</label>'),
    ('placeholder="Nhập lại mật khẩu mới"', 'placeholder="Re-enter new password"'),
    ('<button type="button" class="btn btn-outline" onclick="window.showAdminSettingsModal(event)" style="padding:10px 20px; font-weight:700; border-radius:8px;">Hủy</button>',
     '<button type="button" class="btn btn-outline" onclick="window.showAdminSettingsModal(event)" style="padding:10px 20px; font-weight:700; border-radius:8px;">Cancel</button>'),
    ('<button type="submit" class="btn btn-primary" style="padding:10px 20px; font-weight:700; border-radius:8px; background:var(--color-primary); color:white; border:none; cursor:pointer;">Cập nhật mật khẩu</button>',
     '<button type="submit" class="btn btn-primary" style="padding:10px 20px; font-weight:700; border-radius:8px; background:var(--color-primary); color:white; border:none; cursor:pointer;">Update Password</button>'),
    
    ('window.showToast("Mật khẩu mới phải có tối thiểu 6 ký tự.", "error");', 'window.showToast("New password must be at least 6 characters.", "error");'),
    ('window.showToast("Mật khẩu mới và mật khẩu xác nhận không khớp.", "error");', 'window.showToast("New passwords do not match.", "error");'),
    ('window.showToast("Dịch vụ xác thực chưa sẵn sàng!", "error");', 'window.showToast("Authentication service not ready!", "error");')
]

with open(admin_js_path, 'r', encoding='utf-8') as f:
    content = f.read()

original = content
for src, dest in admin_subs:
    content = content.replace(src, dest)

if content != original:
    with open(admin_js_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Updated {admin_js_path}")
else:
    print(f"No changes in {admin_js_path}")

print("Admin JS translation complete!")
